### PR TITLE
Removed lines that are now in install.sh

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by siddacious — APPROVED** [review]
Looks good to me! @makermelissa merge if you agree

**Review by makermelissa — APPROVED** [review]

**Comment by makermelissa** [comment]
Doh, I just realized we should have left `pip install -r requirements.txt` in here as well. Please add back in on both files @dherrada.

**Comment by siddacious** [comment]
@makermelissa why would we have a second requirements.txt install here?

**Comment by siddacious** [comment]
@makermelissa why would we have a second requirements.txt install here?

**Comment by makermelissa** [comment]
Oh, we already talked about that. Just ignore my comment.

**Pull request merged**
