### PR TITLE
Demonstrate black formatting with pylint, GHA

### PR DESCRIPTION
**Pull request by amyreese**
As suggested by adafruit/cookiecutter-adafruit-circuitpython#63

### CODE REVIEW

**Comment by amyreese** [comment]
Needs https://github.com/adafruit/actions-ci-circuitpython-libs/pull/5 to be accepted so that black is available for use in the build actions.

**Review by tannewt — APPROVED** [review]
This looks good to me! Any other @adafruit/circuitpythonlibrarians have an objection?

**Comment by sommersoft** [comment]
I don't have any _non-opinionated_ objections that would necessarily override standard formatting.

**Comment by sommersoft** [comment]
That wasn't meant to sound that negative. I'm in full support of formatting, and I don't see any issues with how the action step is setup. 😄

**Pull request merged**
